name: Build Electron App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest  # Usa la versión más reciente de macOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Build Electron App (Mac ARM64)
        run: npm run electron:build -- --mac --arm64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-app-macos
          path: dist/**/*.dmg # Ajusta si usas otro formato como .zip o .pkg
